apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudchirp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudchirp
  template:
    metadata:
      labels:
        app: cloudchirp
    spec:
      containers:
        - name: cloudchirp
          image: cloudchirp-app:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/cloudchirp"

---

apiVersion: v1
kind: Service
metadata:
  name: cloudchirp
spec:
  type: NodePort
  selector:
    app: cloudchirp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001